name: Snake Game ðŸ“ˆ

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza toda noite Ã  meia-noite UTC
  workflow_dispatch:     # Permite rodar manualmente no Actions

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositÃ³rio
        uses: actions/checkout@v3

      - name: Gerar SVG da Snake
        uses: Platane/snk@v3
        with:
          github_user_name: thaluanegomes  # Seu usuÃ¡rio do GitHub
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=FF69B4&color_dots=#f8bbd0,#f48fb1,#ec407a,#e91e63,#d81b60

      - name: Commit & Push para branch â€˜outputâ€™
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
